CREATE TABLE IF NOT EXISTS generation_records (
    id SERIAL PRIMARY KEY,
    source_type VARCHAR(20) NOT NULL,
    technique VARCHAR(20) NOT NULL DEFAULT 'black-box',
    source_summary TEXT NOT NULL,
    model_name VARCHAR(80) NOT NULL DEFAULT 'unknown',
    prompt_version VARCHAR(80) NOT NULL DEFAULT 'unknown',
    prompt_used TEXT NOT NULL DEFAULT '',
    llm_raw_output TEXT NOT NULL DEFAULT '',
    generated_cases JSONB NOT NULL,
    structured_requirements JSONB NOT NULL DEFAULT '[]'::jsonb,
    coverage_items JSONB NOT NULL DEFAULT '[]'::jsonb,
    risk_items JSONB NOT NULL DEFAULT '[]'::jsonb,
    state_model JSONB NOT NULL DEFAULT '{}'::jsonb,
    suite_optimization JSONB NOT NULL DEFAULT '{}'::jsonb,
    traceability JSONB NOT NULL DEFAULT '[]'::jsonb,
    test_strategies JSONB NOT NULL DEFAULT '[]'::jsonb,
    engine_metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    engine_ms INTEGER NOT NULL DEFAULT 0,
    llm_ms INTEGER NOT NULL DEFAULT 0,
    total_ms INTEGER NOT NULL DEFAULT 0,
    quality_score NUMERIC(4,2) NOT NULL DEFAULT 0.00,
    tokens_estimate INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
